### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by zhmars** [LooEv/A-bridge-to-YouCompleteMe#1]
你好，七牛云最新的下载无法正常编译，直接下载官方版本是可以编译通过的，下面是编译出错时截图
![123](https://user-images.githubusercontent.com/18466397/29547237-759871f8-872b-11e7-8b99-bcd0f09be3d8.png)

**Comment by LooEv** [comment]
@zhmars 你好，实在抱歉，前一段时间我太忙了，vps过期了，导致七牛云上面的文件有一两个月没有更新了，现在已经重新开始更新了。

**Comment by zhmars** [comment]
没事，辛苦了。

 `deoplete` 最新版本已支持  vim8，所以暂时不用 `YouCompleteMe`。

刚测试了一下，还是不行哦。下载很快，不过还是提示要从 github 上拉取其它 repo，如果可以一步到位就更好了 :)

![image](https://user-images.githubusercontent.com/18466397/31852780-981acbfe-b6b0-11e7-85ba-e5843fc2aba7.png)

**Comment by LooEv** [comment]
尴尬，是一步到位的，我万万没想到 third_party 下面的 ycm 下面还有 submodule，我只运行了一次 git submodule init 然后 git submodule update --recursive，应该使用你给的截图里面的命令：git submodule update --init --recursive。 非常感谢你的指正@zhmars

**Comment by zhmars** [comment]
辛苦了，刚测试，最新下载的可以正常编译了。不过发现另一个问题，貌似 CDN 没有刷新。。

![image](https://user-images.githubusercontent.com/18466397/31859838-85179922-b743-11e7-8cce-5ddf46671268.png)

**Comment by zhmars** [comment]
https://github.com/ycm-core/ycmd/blob/a24204e8382d0660a519f88b59c67026f453c085/build.py#L847

submodule 好像没有自动更新到最新版本，仓库里的 gopls 已经是 v0.4.4，下载的包还是用 v0.4.2 的。

**Comment by zhmars** [comment]
> https://github.com/ycm-core/ycmd/blob/a24204e8382d0660a519f88b59c67026f453c085/build.py#L847
> 
> submodule 好像没有自动更新到最新版本，仓库里的 gopls 已经是 v0.4.4，下载的包还是用 v0.4.2 的。

不对，是我搞错了_(:з」∠)_
